name: Playwright Tests
on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore ./PlaywrightSpecFlow
    - name: Build
      run: dotnet build --no-restore ./PlaywrightSpecFlow
    - name: Installing Browsers and dependencies
      run: pwsh PlaywrightSpecFlow/bin/Debug/net6.0/playwright.ps1 install --with-deps
    - name: Running tests
      env:
        BROWSER: CHROMIUM
      run: xvfb-run dotnet test ./PlaywrightSpecFlow/PlaywrightSpecFlow.csproj -c Debug -f net6.0 --logger:"console;verbosity=detailed" -- Playwright.Retries=1